message(STATUS "INCREMENTING BUILD NUMBER @  ${BUILD_NUMBER_CACHE_FILE}")

if(EXISTS ${BUILD_NUMBER_CACHE_FILE})
   file(READ ${BUILD_NUMBER_CACHE_FILE} APP_VERSION_LIST)   
   LIST(GET APP_VERSION_LIST 0 APP_VERSION_MAJOR)
   LIST(GET APP_VERSION_LIST 1 APP_VERSION_MINOR)
   LIST(GET APP_VERSION_LIST 2 APP_VERSION_PATCH)

    math(EXPR APP_VERSION_PATCH "${APP_VERSION_PATCH}+1")
    file(WRITE ${BUILD_NUMBER_CACHE_FILE} "${APP_VERSION_MAJOR};${APP_VERSION_MINOR};${APP_VERSION_PATCH}")
else()
   file(WRITE ${BUILD_NUMBER_CACHE_FILE} "1;0;0")
endif()

