include(${CMAKE_CURRENT_LIST_DIR}/functions_compile.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/functions_qt.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/functions_target.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/functions_git.cmake)

foreach(COMPONENT ${WaTools_FIND_COMPONENTS})
   #message(STATUS "NEED WaTools component: ${COMPONENT}")
   if(CMAKE_SYSTEM_NAME STREQUAL "iOS")
      #set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
   else()
      find_package(WaTools${COMPONENT} REQUIRED)
   endif()
endforeach()