set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Compute paths
get_filename_component(WAQTTOOLS_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(WAQTTOOLS_INCLUDE_DIRS ${WAQTTOOLS_CMAKE_DIR})

include_directories(${WAQTTOOLS_INCLUDE_DIRS})
