message(STATUS "SET VERSION NUMBERS @ ${BUILD_VERSION_CACHE_FILE}")

if(NOT EXISTS ${BUILD_VERSION_CACHE_FILE})
   set(APP_VERSION_MAJOR 1)
   set(APP_VERSION_MINOR 0)
   file(WRITE ${BUILD_VERSION_CACHE_FILE} "${APP_VERSION_MAJOR};${APP_VERSION_MINOR}")
endif()
    
file(READ ${BUILD_VERSION_CACHE_FILE} APP_VERSION_LIST)   
LIST(GET APP_VERSION_LIST 0 APP_VERSION_MAJOR)
LIST(GET APP_VERSION_LIST 1 APP_VERSION_MINOR)       

string(TIMESTAMP APP_VERSION_TIMESTAMP UTC)

configure_file(
   ${BUILD_VERSION_VERSION_SOURCE_FILE} 
   ${CMAKE_CURRENT_BINARY_DIR}/AppVersionNumber.h
)
