set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Compute paths
get_filename_component(WAMATH_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(WAMATHS_INCLUDE_DIRS ${WAMATH_CMAKE_DIR})

include_directories(${WAMATHS_INCLUDE_DIRS})
